name: Go CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: ['1.23']  # Forced version for consistency

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
        cache: true  # Caching dependencies

    - name: Restore Go Dependencies
      run: go mod download
      working-directory: ./backend_system  # Updated path

    - name: Build
      run: go build -v ./...
      working-directory: ./backend_system  # Updated path

    - name: Run Tests with Coverage
      run: |
        go test -v -coverprofile=coverage.out ./...
        go tool cover -func=coverage.out
      working-directory: ./backend_system  # Updated path

    - name: Upload Coverage and Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: coverage-and-tests
        path: backend_system/coverage.out  # Updated path
